[build]
  command = "NODE_ENV=production npm run build"
  publish = "build"

[[redirects]]
  from = "/api/proxy"
  to = "/.netlify/functions/proxy"
  status = 200
  force = true

[[redirects]]
  from = "/api/create"
  query = {urls = ":urls"}
  to = "/.netlify/builders/create/:urls"
  status = 301

[functions]
  node_bundler = "esbuild"