# sample netlify.toml
[build]
  command = "#"
  functions = "functions/"
  publish = "www"

# note: each of these fields are OPTIONAL
[dev]
  publish = "www"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

  [redirects.headers]
     Access-Control-Allow-Origin = "*"


