# sample netlify.toml
[build]
  command = "npm run build"
  functions = "build-functions"
  publish = "build"

# note: each of these fields are OPTIONAL
[dev]
  functions = "functions"
  publish = "www"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

  [redirects.headers]
     Access-Control-Allow-Origin = "*"


